language: node_js
node_js:
  - "8"
env:
  global:
    - NODE_ENV=development
before_install:
  - cd ../../ && git clone https://github.com/MichMich/MagicMirror
  - mv ianperrin/MMM-Formula1 MagicMirror/modules
  - cd MagicMirror && npm install express
  - cd modules/MMM-Formula1
before_script:
  - npm install grunt-cli -g